IDG_ASEGeoOpt:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    maxstep: null
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
IDG_Packmol:
    box: null
    count:
    - 100
    data_ids: null
    density: 998.20
    pbc: true
    tolerance: 2.0
IDG_SMILES-Water:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: O
MLP_MD_ASEMD:
    data_id: -1
    dump_rate: 100000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    seed: 42
    steps: 200000
    use_momenta: false
    wrap: false
MLP_MD_ASEMD+thermostat:
    friction: 0.01
    temperature: 293.15
    time_step: 0.5
MLP_MD_MixCalculator:
    methods: sum
MLP_MD_MixCalculator+calculators+1:
    abc: false
    cnthr: 8
    cutoff: 8
    damping: bj
    dtype: float32
    skin: 0.0
    xc: pbe
